// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exkkkuoyyzafaqxgafgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4a2trdW95eXphZmFxeGdhZmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NzQ4OTksImV4cCI6MjA3ODQ1MDg5OX0.tA3VGjEa6yF2N-n4TJX5bkymJqzUYrXmDpryDFTGc08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});